import { existsSync } from 'node:fs'
import { join } from 'node:path'
import { app, Menu, Tray, nativeImage } from 'electron'
import { getMainWindow } from './windows/mainWindow'
import { toggleQuickCapture } from './windows/quickCapture'

/**
 * Menu bar (tray) icon — v1.2. The image is a macOS TEMPLATE image (pure black
 * "m" on transparent, generated by scripts/make-icon.sh): the *Template.png
 * naming makes macOS tint it for light/dark menu bars and the pressed state.
 * Dev runs read it from the repo's resources/; packaged builds from
 * process.resourcesPath/tray — shipped via extraResources in electron-builder.yml,
 * because buildResources itself is NOT packaged.
 *
 * Default ON: created unless 'ui.menuBarIcon' is explicitly false. Settings →
 * General toggles it live via settings:set in handlers.ts (same pattern as
 * embeddings.consent) → setTrayEnabled.
 */

let tray: Tray | null = null
let openMainWindowFn: (() => void) | null = null

function trayImagePath(): string {
  return app.isPackaged
    ? join(process.resourcesPath, 'tray', 'trayTemplate.png')
    : join(app.getAppPath(), 'resources', 'tray', 'trayTemplate.png')
}

function showMainWindow(): void {
  const win = getMainWindow()
  if (win) {
    if (win.isMinimized()) win.restore()
    win.show()
    win.focus()
  } else {
    openMainWindowFn?.()
  }
}

function createTray(): void {
  if (tray) return
  const imagePath = trayImagePath()
  if (!existsSync(imagePath)) {
    // Missing asset must never take the app down — run `npm run icon`.
    console.error('[tray] template image missing:', imagePath)
    return
  }
  // createFromPath picks the @2x.png sibling up automatically for Retina.
  const image = nativeImage.createFromPath(imagePath)
  image.setTemplateImage(true) // belt and braces — the Template suffix already marks it
  tray = new Tray(image)
  tray.setToolTip('myMem')
  // No click handler: left-click opens the context menu (default macOS behavior).
  tray.setContextMenu(
    Menu.buildFromTemplate([
      { label: 'Open myMem', click: showMainWindow },
      {
        label: 'Quick Capture',
        // Display hint only — the real binding is the globalShortcut in index.ts
        // (registerAccelerator: false keeps Electron from registering it twice).
        accelerator: 'Control+Command+Space',
        registerAccelerator: false,
        click: () => toggleQuickCapture()
      },
      { type: 'separator' },
      { label: 'Quit myMem', click: () => app.quit() }
    ])
  )
}

function destroyTray(): void {
  tray?.destroy()
  tray = null
}

/** index.ts (whenReady, non-smoke): wires the open-window callback and applies the saved setting. */
export function initTray(opts: { openMainWindow: () => void; enabled: boolean }): void {
  openMainWindowFn = opts.openMainWindow
  setTrayEnabled(opts.enabled)
}

/** Live toggle — called from handlers.ts when 'ui.menuBarIcon' changes. */
export function setTrayEnabled(enabled: boolean): void {
  if (enabled) createTray()
  else destroyTray()
}
